spring:
  thymeleaf:
    cache: false # 禁用 thymeleaf 模板缓存
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.162.54:3306/km?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8 #&useSSL=true
    username: root
    password: qweqwe