server:
  port: 8801

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.162.54:3306/km?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8 #&useSSL=true
    username: root
    password: qweqwe

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.by.km.entity